project:
  type: website
  # output-dir: docs

website:
  open-graph: true
  site-url: https://www.leonardo-guedez.com/
  # cookie-consent: 
  #   type: express 
  #   style: headline
  #   palette: dark
  favicon: images/github-mark-white.png
  google-analytics: 
    tracking-id: "G-LW03VL0YTS" #"UA-242992767-1"
    anonymize-ip: true
  title: "Leo Guédez"
  navbar:
    title: false
    logo: images/logos/logo-dark.png
    logo-alt: "The name 'sam csik' written in green text. Above 'csik' is a dark green horizontal line, above which sits a green chick icon."
    right:
      - href: index.qmd
        text: home
      - about.qmd
      # - href: talks_workshops.qmd
        # text: talks & workshops
      # - href: courses.qmd
        # text: courses
      - href: projects.qmd
        text: projects
      - posts.qmd
      # - resources.qmd
      # - href: CV/SCsik_CV.pdf
      #   text: cv
      #   target: _blank
      - text: get in touch!
        menu:
          - icon: twitter
            text: Twitter
            href: https://twitter.com/eleguedez
            target: _blank
          - icon: linkedin
            text: LinkedIn
            href: https://linkedin.com/in/lguedez
            target: _blank
          - icon: envelope
            text: email
            href: mailto:guedezle@msu.edu
      # - icon: github
        # href: https://github.com/samanthacsik/samanthacsik.github.io
        # target: _blank

format:
  html:
    page-layout: full
    sidebar: false
    theme: 
      - styles.scss
    # css: styles.css
    mainfont: Nunito
    toc: true


