project:
  type: website
  output-dir: docs

website:
  open-graph: true
  site-url: https://www.leonardo-guedez.com/
  title: "Leo Guédez"
  favicon: "images/github-mark-white.png"
  # cookie-consent: 
  #   type: express 
  #   style: headline
  #   palette: dark
  # google-analytics: 
    # tracking-id: ""
    # anonymize-ip: true
  navbar:
    title: false
    right:
      - href: index.qmd
        text: home
      - about.qmd
      # - href: talks_workshops.qmd
        # text: talks & workshops
      # - href: courses.qmd
        # text: courses
      - href: projects.qmd
        text: projects
      - posts.qmd
      # - resources.qmd
      # - href: CV/SCsik_CV.pdf
      #   text: cv
      #   target: _blank
      - text: get in touch!
        menu:
          - icon: twitter
            text: Twitter
            href: https://twitter.com/SamanthaCsik
            target: _blank
          - icon: linkedin
            text: LinkedIn
            href: https://www.linkedin.com/in/samanthacsik/
            target: _blank
          - icon: envelope
            text: email
            href: mailto:scsik@ucsb.edu
      # - icon: github
      #   href: https://github.com/samanthacsik/samanthacsik.github.io
      #   target: _blank

format:
  html:
    page-layout: full
    sidebar: false
    theme: 
      - styles.scss
    # css: styles.css
    mainfont: Nunito
    toc: true


