project:
  type: website
  output-dir: docs

website:
  open-graph: true
  site-url: https://www.leonardo-guedez.com/
  # cookie-consent: 
  #   type: express 
  #   style: headline
  #   palette: dark
  favicon: images/github-mark-white.png
  # google-analytics: 
  #   tracking-id: "G-LW03VL0YTS"
  #   anonymize-ip: true
  title: "Leo Guédez"
  navbar:
    title: false
    logo: images/logos/logo-dark.png
    # logo-alt: ""
    right:
      - href: index.qmd
        text: home
      - about.qmd
      - href: projects.qmd
        text: projects
      - text: get in touch!
        menu:
          - icon: linkedin
            text: LinkedIn
            href: https://linkedin.com/in/lguedez
            target: _blank
          # - icon: 𝕏 Twitter
            # text: 𝕏 Twitter
            # href: https://twitter.com/eleguedez
            # target: _blank
          - icon: envelope
            text: email
            href: mailto:eleguedez@protonmail.com

format:
  html:
    page-layout: full
    sidebar: false
    theme: 
      - styles.scss
    # css: styles.css
    mainfont: Kohinoor Bangla
    toc: true


