project:
  type: website
  output-dir: content

website:
  open-graph: true
  site-url: https://www.leonardo-guedez.com/
  title: "Leo Guédez"
  
  favicon: "images/github-mark-white.png"
  # google-analytics: 
    # tracking-id: ""
    # anonymize-ip: true
  
  navbar:
    # logo: "node-tree-diagram.png"
    right:
      - href: index.qmd
        text: Home
      # - about.qmd # for later expansion, like in here: https://samanthacsik.github.io/about.html
      - href: projects.qmd
        text: Projects
        
      - href: CV/leo-guedez-CV.pdf
        text: CV 

      - icon: linkedin
        href: https://linkedin.com/in/lguedez
        aria-label: Quarto LinkedIn
      - icon: twitter
        href: https://twitter.com/eleguedez
        aria-label: Quarto Twitter
      # - icon: github
      #   href: https://github.com/leonardo-guedez
      #   aria-label: Quarto Github

  search: 
    location: navbar
    type: overlay

format:
  html:
    grid:
      sidebar-width: 100px
      body-width: 700px
      margin-width: 700px
      # gutter-width: 1.5rem
    theme:
      light: [flatly, theme_light_custom.scss]
      dark: [flatly, theme_dark_custom.scss]
    css: styles.css
    page-layout: full
    # citations-hover: true
    # code-link: true
    # code-fold: show
    # code-tools: false
    code-block-border-left: "#004E4F"

editor: visual

execute:
  freeze: auto

resources:
  - CNAME
